// helpers/codesandbox/codesandbox-react.helper.ts
import lernaJson from "../../lerna.json";
import { generateCodeSandboxLink } from "./codesandbox.helper";

export function generateReactCodeSandboxLink(options) {
  const { components, code, dependencies } = options;

  const html = `<div class="app" id="root"></div>`;

  const previewCode = `import { ${components.join(
    ', '
  )} } from '@snowfox/react';
import '@snowfox/react/dist/snowfox.css';

const App = () => (${code}
);
`;

  const demoCode = `
import React from 'react';
import ReactDOM from 'react-dom';

${previewCode}

ReactDOM.render(
  <App />,
  document.getElementById("root")
)
`.trim();

  const projectDependencies = {
    ...dependencies,
    react: '16.8.0',
    'react-dom': '16.8.0',
    '@snowfox/react': `${lernaJson.version}`
  };

  const devDependencies = {
    'react-scripts': 'latest'
  };

  const { url } = generateCodeSandboxLink({
    html,
    demoCode,
    dependencies: projectDependencies,
    devDependencies
  });

  return { url, content: previewCode };
}

// helpers/codesandbox/codesandbox-solid.helper.ts
import lernaJson from "../../lerna.json";
import { generateCodeSandboxLink } from "./codesandbox.helper";

export function generateSolidCodeSandboxLink(options) {
  const { components, code, dependencies } = options;

  const html = `<div class="app" id="app"></div>
<script src="index.tsx"></script>`;

  const previewCode = `import { ${components.join(
    ', '
  )} } from '@snowfox/solid';
import '@snowfox/solid/dist/snowfox.css';

const App: Component = () => (${code}
);
`;

  const demoCode = `
import { Component } from "solid-js";
import { render } from "solid-js/web";

${previewCode}

render(() => <App />, document.getElementById("app"));
`.trim();

  const extraFiles = {
    '.babelrc': {
      content: `{
      "presets": [
        "env",
        "babel-preset-solid",
        "@babel/preset-typescript"
      ]
    }`
    }
  };

  const projectDependencies = {
    ...dependencies,
    '@babel/core': '7.14.6',
    '@babel/preset-typescript': '7.14.5',
    'babel-preset-solid': '1.0.0',
    'solid-js': '1.4.3',
    '@snowfox/solid': `${lernaJson.version}`
  };

  const devDependencies = {
    'parcel-bundler': '^1.6.1',
    typescript: '^4.2.0'
  };

  const { url } = generateCodeSandboxLink({
    html,
    demoCode,
    dependencies: projectDependencies,
    devDependencies,
    extraFiles,
    isTypescript: true,
    isJSX: true
  });

  return { url, content: previewCode };
}
